### ISSUE TITLE
Plaster and Composer Removal/Relocation

### ISSUE THREAD

**Issue by Shambles-Dev** [rshipp/ahk-libs#4]
I plan on removing Plaster and Composer from my GitHub to reduce clutter, since I have abandoned them.

They can still be found on the AutoHotkey forum:
Plaster: http://ahkscript.org/boards/viewtopic.php?t=3924
Composer: http://ahkscript.org/boards/viewtopic.php?t=4902
I do not plan on ever removing them from the forums.

The reason for their abandonment is discussed in the sections at the top of their forum posts and here:
http://ahkscript.org/boards/viewtopic.php?t=6969

I apologize for any inconvenience.  This message is my attempt to minimize that.

Thank you for your interest in my work.

**Comment by rshipp** [comment]
Thanks for the heads up!
