### ISSUE TITLE
FTP.ahk doesn't work for me unless I change the code to use passive mode

### ISSUE THREAD

**Issue by Cerberus-tm** [rshipp/ahk-libs#6]
I'm a total layman with respect to FTP, but here is my experience. It didn't work for me when I tried the example; that is, I got files with a size of 0 bytes and other errors. It did work when I changed line 112. It was this:
`this.InternetConnectFlags := 0`
I changed it into this in order to use passive mode:
`this.InternetConnectFlags := 0x08000000 ; Passive mode`
I got the code from this forum post:
https://autohotkey.com/board/topic/68473-ftp-class-library-ftp-as-easy-as-1-2-3/page-3#entry635216
So I don't understand what passive mode does or anything, but it might be nice to have this message here as a warning to future users.

**Comment by rshipp** [comment]
Linked to this issue from the README.
